[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "autodir"
version = "0.1.0"
description = "A CLI tool for generating project structures from Markdown"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.27.1,<1.0"
]
authors = [
    { name = "Hrishikesh" }
]

[project.scripts]
autodir = "scaffolder.cli:app"

[tool.setuptools.packages.find]
where = ["src"]